version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pdftools-backend
    container_name: pdftools_backend
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    ports:
      - "127.0.0.1:9002:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pdftools_network
      - mysql_default
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pdftools-frontend
    container_name: pdftools_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - pdftools_network
    depends_on:
      - backend

networks:
  pdftools_network:
    driver: bridge

  mysql_default:
    external: true
